server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service-route
          uri: lb://customer-service # Load balanced URI to `customer-service`
          predicates:
            - Path=/customers/**



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/